version: '3'

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly-data:/data
    command: --requirepass Yqdm4sCcLjxsFAtL9auKM4tjFRravbEZ
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped

volumes:
  dragonfly-data: