services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly-data:/data
    command: --requirepass Yqdm4sCcLjxsFAtL9auKM4tjFRravbEZ
    deploy:
      resources:
        limits:
          memory: 6G
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    ports:
      - "6317:5432"
    environment:
      POSTGRES_DB: academicweapon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fEmGFZabG3cdxevct3v73Z9o9V0VpFG2E
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 6G
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d academicweapon"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dragonfly-data:
  postgres-data: